language: python
python:
 - "2.7"
 - "3.6"
 - "3.7"

env:
  matrix:
   - CELERY="celery<4.0"
   - CELERY="celery<5.0"

install: 
  - pip install -U pip
  - pip install codecov
  - pip install "$CELERY"
  - pip install -r requirements_dev.txt

before_script:
  - pip freeze

script: 
  - py.test --cov celery_mock
  - flake8 .

after_success:
  - codecov
