language: python
python:
 - "3.6"
 - "3.7"

env:
  matrix:
   - CELERY="celery<4.0"
   - CELERY="celery<5.0"

install: 
  - pip install -U pip
  - pip install poetry==1.1.2
  - poetry config virtualenvs.create false && poetry install
  - pip install "$CELERY"

before_script:
  - pip freeze

script: 
  - py.test --cov celery_mock
  - flake8 .

after_success:
  - codecov
